---
- name: Get host data from deployment plan
  ansible.builtin.set_fact:
    configure_image_hosts_host_ip: "{{ configure_image_hosts_updated_hosts_data.keys() | first }}"
  when: configure_image_hosts_new_vm_created

- name: Set host data based on deployment plan
  ansible.builtin.set_fact:
    configure_image_hosts_host_vm_data:
      - hostname: "{{ configure_image_hosts_host_ip }}"
        vms: "{{ hostvars[configure_image_hosts_host_ip].gather_host_facts_host_vms }}"
  when: configure_image_hosts_new_vm_created

- name: Use all hosts data if new VM was already created
  ansible.builtin.set_fact:
    configure_image_hosts_host_vm_data: "{{ configure_image_hosts_all_hosts_data }}"
  when: not configure_image_hosts_new_vm_created

- name: Analyze VMs
  analyze_vm_groups:
    hosts_data: "{{ configure_image_hosts_host_vm_data }}"
    vm_name: "{{ configure_image_hosts_vm_name }}"
  register: configure_image_hosts_group_analysis

- name: Find item where group_vms_count is 1
  ansible.builtin.set_fact:
    configure_image_hosts_filtered_vm_info: "{{ configure_image_hosts_group_analysis.hosts_group_data | selectattr('group_vms_count', 'equalto', 1) | first }}"

- name: Add VM host to inventory
  ansible.builtin.add_host:
    name: "{{ configure_image_hosts_filtered_vm_info.hostname }}"
    groups: "image_hosts"
    vm: "{{ configure_image_hosts_filtered_vm_info.group_vms[0] }}"
