---
- name: Add storage VLAN
  network_setup:
    name: "{{ configure_storage_interface_msdc_name }}"
    device: en0
    tag: "{{ msdc_storage_vlan }}"
    ip: "{{ configure_storage_interface_msdc_storage_network_address }}"
    mask: "{{ configure_storage_interface_msdc_storage_network_mask }}"
  when: not configure_storage_interface_msdc_remove | bool

- name: Remove storage VLAN
  network_setup:
    name: "{{ configure_storage_interface_msdc_name }}"
    device: en0
    tag: "{{ msdc_storage_vlan }}"
    state: absent
  when: configure_storage_interface_msdc_remove | bool
