---
- name: Install Orka Engine
  hosts: hosts
  gather_facts: false
  pre_tasks:
    - name: Install Dev Tools
      ansible.builtin.include_role:
        name: install_dev_tools

    - name: Gather minimal facts
      ansible.builtin.setup:
        filter:
          - "ansible_env"
  roles:
    - role: install_engine
      vars:
        install_engine_pkg_url: "{{ engine_url | default('https://distribution.macstadium.com/orka-engine/official/3.5.2/orka-engine.pkg') }}"
