---
- name: Install Android SDK on target hosts
  hosts: hosts
  gather_facts: false
  module_defaults:
    ansible.builtin.setup:
      gather_timeout: 20
  pre_tasks:
    - name: Gather minimal facts
      ansible.builtin.setup:
        filter:
          - "ansible_env"
          - "ansible_user_gid"
      tags:
        - always
  roles:
    - role: install_homebrew
      tags:
        - orka-tools
    - role: install_android_sdk
      tags:
        - android-sdk
    - role: install_orka_android_tools
      tags:
        - orka-tools
