---
- name: Uninstall Android platform and system image
  hosts: hosts
  gather_facts: false
  roles:
    - role: sdkmanager_uninstall
      sdkmanager_uninstall_platform: "{{ platform | default('android-36') }}"
  tags:
    - sdkmanager
