---
- name: Check if orka-engine is installed
  ansible.builtin.stat:
    path: /usr/local/bin/orka-engine
  register: install_engine_check
  changed_when: false

- name: Install and activate Orka Engine
  when: not install_engine_check.stat.exists or install_engine_force | bool
  block:
    - name: Download PKG file
      ansible.builtin.get_url:
        url: "{{ install_engine_pkg_url }}"
        dest: "{{ install_engine_pkg_path }}"
        force: true
        mode: "0644"

    - name: Install PKG file
      become: true
      ansible.builtin.command: installer -pkg "{{ install_engine_pkg_path }}" -target /
      changed_when: true

    - name: Clean up downloaded PKG file
      ansible.builtin.file:
        path: "{{ install_engine_pkg_path }}"
        state: absent

    - name: Override Orka Engine CLI helper
      become: true
      ansible.builtin.template:
        src: "orka-engine.sh.j2"
        dest: "{{ install_engine_helper_path }}"
        mode: "0755"

    - name: Deploy launch daemon
      become: true
      ansible.builtin.template:
        src: "com.macstadium.orka-engine.server.managed.plist.j2"
        dest: "{{ install_engine_service_path }}"
        mode: "0644"

    - name: Run Orka Engine Server
      community.general.launchd:
        name: "{{ install_engine_service_id }}"
        state: restarted
        enabled: true
      become: true
