---
- name: Create admin user account
  ansible.builtin.user:
    name: "{{ provision_user_username }}"
    password: "{{ provision_user_password }}"
    groups: admin
    state: present
  become: true
