---
- name: Check if Python is installed
  ansible.builtin.raw: python3 --version
  register: install_dev_tools_python_output
  ignore_errors: true
  changed_when: false

- name: Install Dev Tools
  when: install_dev_tools_python_output.rc != 0
  block:
    - name: Prepare to Install Command Line Tools
      ansible.builtin.raw: touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
      changed_when: true

    - name: Search for Command Line Tools Package
      ansible.builtin.raw: >
        softwareupdate -l |
        grep -B 1 -E 'Command Line Tools' |
        awk -F'*' '/^\*/ {print $2}' |
        sed -e 's/^ *Label: //' -e 's/^ *//' |
        sort -V |
        tail -n1
      register: install_dev_tools_software_update_result
      changed_when: false

    - name: Install Command Line Tools
      ansible.builtin.raw: softwareupdate -i '{{ install_dev_tools_software_update_result.stdout | regex_search('Command Line Tools for Xcode(.)+', ignorecase=True) | trim
        }}'
      register: install_dev_tools_install_result
      failed_when: '"No such update" in install_dev_tools_install_result.stdout'
      changed_when: true
  always:
    - name: Remove Installation Lock File
      ansible.builtin.raw: rm /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
      changed_when: true
